
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/usr/local/Cellar/cmake/3.26.1/share/cmake/Modules/CMakeDetermineSystem.cmake:199 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Emscripten - 1 - x86
      The host system is: Darwin - 24.6.0 - x86_64
...
